// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4aowX7q2qz27K5WyNNzlsTeZtsfauRqM',
    appId: '1:201661320596:android:3a7fd5484c0a4a7b5ed381',
    messagingSenderId: '201661320596',
    projectId: 'shoppingapp-3d7c4',
    storageBucket: 'shoppingapp-3d7c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOVJLJNdl45Q58hMvmZ_KrgSPy-HSoKr8',
    appId: '1:201661320596:ios:636ad1b9db6406405ed381',
    messagingSenderId: '201661320596',
    projectId: 'shoppingapp-3d7c4',
    storageBucket: 'shoppingapp-3d7c4.firebasestorage.app',
    androidClientId: '201661320596-kd4jbp46skmlkfioppuiof7fogr16qao.apps.googleusercontent.com',
    iosClientId: '201661320596-o66iqbf3bae5qrnh111aodrb1tcc00ee.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseGetx',
  );

}